org: jsstrn
app: subhas-music-bot
service: subhas-music-bot

frameworkVersion: "2"

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: src/functions/index.hello
    events:
      - http:
          path: hello
          method: GET
  
  handleBotRequests:
    handler: src/functions/index.handleBotRequests
    events:
      - http:
          path: handleBotRequests
          method: POST

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-offline
