org: jsstrn
app: subhas-music-bot
service: subhas-music-bot

frameworkVersion: "2"
useDotenv: true

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  setWebhook:
    handler: src/functions/index.setWebhook
    events:
      - http:
          path: setWebhook
          method: GET

  handleBotRequests:
    handler: src/functions/index.handleBotRequests
    events:
      - http:
          path: handleBotRequests
          method: POST
      - s3:
          bucket: ${self:app}-${opt:stage}-music-tracks

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-offline
