version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  node: circleci/node@4.5.1
  serverless: circleci/serverless-framework@1.0.1

jobs:
  deploy:
    executor: serverless/default
    parameters:
      stage:
        type: string
        default: dev
    steps:
      - checkout
      - aws-cli/setup
      - node/install-packages
      - serverless/setup:
          org-name: jsstrn
          app-name: subhas-music-bot
      - run:
          name: Create .env file
          command: ./circleci/create-env
      - run:
          name: Deploy application to << parameters.stage >> environment
          command: npm run "deploy-to-<< parameters.stage >>"

workflows:
  deployment:
    jobs:
      - node/test:
          name: unit-tests
          version: "14.17"

      - deploy:
          name: deploy-dev
          stage: dev
          context:
            - music-bot-dev
            - aws-credentials
            - serverless-credentials
          requires:
            - unit-tests

      - approve-deploy-stage:
          name: approve-deploy-stage
          type: approval
          requires:
            - deploy-dev

      - deploy:
          name: deploy-stage
          stage: stage
          context:
            - music-bot-stage
            - aws-credentials
            - serverless-credentials
          requires:
            - approve-deploy-stage

      - approve-deploy-prod:
          name: approve-deploy-prod
          type: approval
          requires:
            - deploy-stage

      - deploy:
          name: deploy-prod
          stage: prod
          context:
            - music-bot-prod
            - aws-credentials
            - serverless-credentials
          requires:
            - approve-deploy-prod
