version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  node: circleci/node@4.5.1
  serverless: circleci/serverless-framework@1.0.1

jobs:
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          org-name: jsstrn
          app-name: subhas-music-bot
      - run:
          name: Deploy application to development environment
          command: npm run "deploy:<< parameters.stage >>"

workflows:
  deployment:
    jobs:
      - node/test:
          version: "14.17"
      
      - deploy:
          stage: dev
          context:
            - aws-credentials
            - serverless-credentials
          requires:
            - node/test
      
      - deploy:
          stage: stage
          type: approval
          context:
            - aws-credentials
            - serverless-credentials
          requires:
            - deploy
      
      - deploy:
          stage: prod
          type: approval
          context:
            - aws-credentials
            - serverless-credentials
          requires:
            - deploy
