const FLAGSMITH_API_KEY = process.env.FLAGSMITH_API_KEY;
const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const S3_BUCKET_NAME = process.env.S3_BUCKET_NAME;
const S3_REGION = process.env.S3_REGION;

export { FLAGSMITH_API_KEY, TELEGRAM_BOT_TOKEN, S3_BUCKET_NAME, S3_REGION };
